/* Generated by `uv run python -m contracts_py.export` from packages/contracts-py. Do not edit. */

/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Sector".
 */
export type Sector =
  | "technology_saas"
  | "financial_services"
  | "banking"
  | "insurance"
  | "healthcare"
  | "pharma_life_sciences"
  | "manufacturing"
  | "retail_ecommerce"
  | "telecom"
  | "energy_utilities"
  | "logistics_transport"
  | "media_entertainment"
  | "professional_services"
  | "education"
  | "public_sector"
  | "nonprofit"
  | "other";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "BusinessModel".
 */
export type BusinessModel = "b2b" | "b2c" | "b2b2c" | "marketplace" | "public_service" | "mixed";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "SizeBand".
 */
export type SizeBand = "startup" | "smb" | "mid_market" | "enterprise" | "large_enterprise";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "StrengthCategory".
 */
export type StrengthCategory = "capability" | "expertise" | "process" | "asset" | "relationship" | "data";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "EntityType".
 */
export type EntityType =
  | "department"
  | "person_token"
  | "role"
  | "knowledge_asset"
  | "system"
  | "vendor"
  | "project"
  | "workflow"
  | "control"
  | "kpi"
  | "customer_segment"
  | "dataset";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Criticality".
 */
export type Criticality = "low" | "medium" | "high" | "critical";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Sensitivity".
 */
export type Sensitivity = "general" | "finance" | "hr" | "customer" | "security";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Relation".
 */
export type Relation =
  | "OWNS"
  | "BACKS_UP"
  | "KNOWS"
  | "MAINTAINS"
  | "RUNS"
  | "PROVIDES"
  | "CONSUMES"
  | "DEPENDS_ON"
  | "SUPPORTS"
  | "FUNDS"
  | "CONTROLS"
  | "CONTRIBUTES_TO"
  | "SUBSTITUTES_FOR"
  | "FLOWS_TO";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ChannelKind".
 */
export type ChannelKind = "constraint" | "budget" | "capability" | "signal" | "value";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "PressureKind".
 */
export type PressureKind = "cost_growth" | "renewal_step" | "hazard" | "kpi_drift" | "budget_ceiling" | "deadline";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ActionType".
 */
export type ActionType =
  | "assess_change"
  | "remove_vendor"
  | "reduce_capacity"
  | "add_capacity"
  | "remove_roles"
  | "stop_project"
  | "start_project"
  | "delay_project"
  | "invest";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "MitigationType".
 */
export type MitigationType =
  | "reassign_owner"
  | "document_runbook"
  | "reassign_on_call"
  | "add_replacement_feed"
  | "resequence_project"
  | "retain_capacity_temporarily";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DocumentType".
 */
export type DocumentType =
  | "contract"
  | "policy"
  | "runbook"
  | "sop"
  | "architecture_note"
  | "org_chart"
  | "budget_report"
  | "financial_forecast"
  | "kpi_report"
  | "incident_report"
  | "audit_report"
  | "workflow_map"
  | "knowledge_matrix"
  | "meeting_minutes"
  | "strategy_memo"
  | "other";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DocumentStatus".
 */
export type DocumentStatus = "current" | "outdated" | "draft" | "archived";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "EvidenceSource".
 */
export type EvidenceSource =
  | "contract"
  | "workflow_map"
  | "system_ownership"
  | "kpi_definition"
  | "runbook"
  | "architecture_note"
  | "activity_log"
  | "knowledge_matrix"
  | "policy"
  | "incident"
  | "finance_forecast";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Future".
 */
export type Future = "act_now" | "inaction" | "delay" | "alternative";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "RiskAppetite".
 */
export type RiskAppetite = "conservative" | "balanced" | "aggressive";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DecisionType".
 */
export type DecisionType =
  | "cost_reduction"
  | "vendor_consolidation"
  | "capacity_change"
  | "project_decision"
  | "investment"
  | "restructure"
  | "mixed";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "InterventionKind".
 */
export type InterventionKind = "action" | "mitigation";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ImpactLevel".
 */
export type ImpactLevel = "direct" | "dependent" | "second_order" | "delayed" | "feedback";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ImpactCategory".
 */
export type ImpactCategory = "ownership" | "technical" | "operational" | "business" | "compliance" | "financial";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Polarity".
 */
export type Polarity = "benefit" | "harm";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Direction".
 */
export type Direction = "increase" | "decrease" | "no_change";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Origin".
 */
export type Origin = "engine" | "agent" | "challenger" | "user";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ClaimStatus".
 */
export type ClaimStatus = "computed" | "validated" | "hypothesis" | "rejected";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "RiskLevel".
 */
export type RiskLevel = "low" | "medium" | "high" | "critical";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "MigrationDifficulty".
 */
export type MigrationDifficulty = "low" | "medium" | "high";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "EventType".
 */
export type EventType =
  | "run_created"
  | "phase_changed"
  | "scenario_created"
  | "pressure_activated"
  | "candidate_generated"
  | "candidate_rejected"
  | "agent_started"
  | "agent_completed"
  | "agent_failed"
  | "dependency_validated"
  | "impact_computed"
  | "constraint_violated"
  | "challenge_raised"
  | "simulation_completed"
  | "futures_compared"
  | "portfolio_ranked"
  | "blast_radius_ready"
  | "mitigation_applied"
  | "package_ready"
  | "human_decision_recorded"
  | "question_selected"
  | "answer_received"
  | "settings_updated"
  | "document_registered"
  | "run_failed";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "RunStatus".
 */
export type RunStatus =
  | "created"
  | "validating"
  | "building_futures"
  | "running_agents"
  | "propagating"
  | "challenging"
  | "optimizing"
  | "comparing_futures"
  | "mitigating"
  | "generating_package"
  | "awaiting_approval"
  | "completed"
  | "failed";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "EventLog".
 */
export type EventLog = Event[];
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "UserRole".
 */
export type UserRole = "viewer" | "approver";
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "OverlapDimension".
 */
export type OverlapDimension =
  | "record_coverage"
  | "attribute_coverage"
  | "geography"
  | "history_depth"
  | "freshness"
  | "accuracy"
  | "permitted_use"
  | "consumer_teams"
  | "downstream_workflows"
  | "model_features"
  | "substitutability";

export interface CanaryContracts {
  Twin: Twin;
  Organization: Organization;
  DepartmentProfile: DepartmentProfile;
  Entity: Entity;
  Edge: Edge;
  Pressure: Pressure;
  Document: Document;
  Evidence: Evidence;
  OrganizationSettings: OrganizationSettings;
  SectorPreset: SectorPreset;
  AgentView: AgentView;
  ValidationIssue: ValidationIssue;
  DomainGraph: DomainGraph;
  DepartmentDetail: DepartmentDetail;
  DecisionBrief: DecisionBrief;
  Intervention: Intervention;
  Constraint: Constraint;
  CandidatePlan: CandidatePlan;
  Scenario: Scenario;
  Impact: Impact;
  SimulationResult: SimulationResult;
  FutureComparison: FutureComparison;
  PortfolioComparison: PortfolioComparison;
  MitigationComparison: MitigationComparison;
  BlastRadius: BlastRadius;
  VendorOverlap: VendorOverlap;
  KnowledgeCoverage: KnowledgeCoverage;
  ItemCounterfactual: ItemCounterfactual;
  MissingQuestion: MissingQuestion;
  UserAnswer: UserAnswer;
  AgentSpec: AgentSpec;
  AgentContext: AgentContext;
  AgentOutput: AgentOutput;
  ChallengerOutput: ChallengerOutput;
  AgentAssessment: AgentAssessment;
  DecisionPackage: DecisionPackage;
  HumanDecision: HumanDecision;
  Event: Event;
  EventLog: EventLog;
  RunState: RunState;
  HealthResponse: HealthResponse;
  DecisionCreated: DecisionCreated;
  DecisionPromptRequest: DecisionPromptRequest;
  DecisionDraft: DecisionDraft;
  HumanDecisionRequest: HumanDecisionRequest;
  QuickSimulateRequest: QuickSimulateRequest;
  FuturesRequest: FuturesRequest;
  OptimizeRequest: OptimizeRequest;
  ReplayInfo: ReplayInfo;
  ReplayStarted: ReplayStarted;
  OrganizationProfileView: OrganizationProfileView;
  SignupRequest: SignupRequest;
  LoginRequest: LoginRequest;
  UserPublic: UserPublic;
  AuthToken: AuthToken;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Twin".
 */
export interface Twin {
  schema_version?: "2.1.0" | "2.1.1";
  version: VersionInfo;
  organization: Organization;
  department_profiles?: DepartmentProfile[];
  entities?: Entity[];
  edges?: Edge[];
  pressures?: Pressure[];
  documents?: Document[];
  evidence?: Evidence[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "VersionInfo".
 */
export interface VersionInfo {
  twin_version: string;
  settings_version: number;
  prompt_version: string;
  model_id: string;
  engine_version: string;
  created_at: string;
  as_of_date: string;
  data_snapshot_id?: string | null;
  policy_version?: string | null;
  coefficient_version?: string | null;
  created_by?: string | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Organization".
 */
export interface Organization {
  id: string;
  legal_name: string;
  display_name: string;
  sector: Sector;
  sub_sector?: string | null;
  secondary_sectors?: Sector[];
  business_model: BusinessModel;
  size_band: SizeBand;
  headquarters_country: string;
  operating_regions?: string[];
  annual_revenue_usd: number;
  total_annual_budget_usd: number;
  total_headcount_fte: number;
  fiscal_year_start_month: number;
  regulatory_frameworks?: string[];
  strategic_priorities?: StrategicPriority[];
  description: string;
  evidence_refs?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "StrategicPriority".
 */
export interface StrategicPriority {
  id: string;
  text: string;
  rank: number;
  kpi_ids?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DepartmentProfile".
 */
export interface DepartmentProfile {
  department_id: string;
  mission: string;
  head_role_id?: string | null;
  agent_id?: string | null;
  staffing: StaffingStrength;
  budget: DepartmentBudget;
  /**
   * @minItems 1
   */
  strengths: [DepartmentStrength, ...DepartmentStrength[]];
  gaps?: DepartmentGap[];
  maturity_level: number;
  owned_entity_ids?: string[];
  critical_workflow_ids?: string[];
  kpi_ids?: string[];
  document_ids?: string[];
  documentation_coverage?: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "StaffingStrength".
 */
export interface StaffingStrength {
  sanctioned_fte: number;
  actual_fte: number;
  contractors_fte: number;
  open_positions: number;
  attrition_rate_annual: number;
  avg_time_to_hire_days: number;
  utilisation: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DepartmentBudget".
 */
export interface DepartmentBudget {
  annual_budget_usd: number;
  spent_ytd_usd: number;
  fixed_cost_pct: number;
  budget_owner_role_id?: string | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DepartmentStrength".
 */
export interface DepartmentStrength {
  id: string;
  name: string;
  category: StrengthCategory;
  level: number;
  supports_entity_ids?: string[];
  key_role_ids?: string[];
  concentration: number;
  evidence_refs?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DepartmentGap".
 */
export interface DepartmentGap {
  id: string;
  name: string;
  category: StrengthCategory;
  severity: number;
  affected_entity_ids?: string[];
  evidence_refs?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Entity".
 */
export interface Entity {
  id: string;
  type: EntityType;
  name: string;
  department_id?: string | null;
  criticality?: Criticality;
  sensitivity?: Sensitivity;
  annual_cost_usd?: number | null;
  one_time_exit_cost_usd?: number | null;
  migration_cost_usd?: number | null;
  capacity_fte?: number | null;
  min_qualified_owners?: number | null;
  documented_pct?: number | null;
  failure_cost_per_day_usd?: number | null;
  customer_facing?: boolean | null;
  completion_pct?: number | null;
  remaining_cost_usd?: number | null;
  expected_completion_day?: number | null;
  retires_entity_ids?: string[];
  role_id?: string | null;
  kpi_baseline?: number | null;
  kpi_unit?: string | null;
  higher_is_better?: boolean | null;
  mandatory?: boolean | null;
  framework?: string | null;
  arr_usd?: number | null;
  tags?: string[];
  evidence_refs?: string[];
  geographies?: string[];
  history_years?: number | null;
  freshness_days?: number | null;
  accuracy?: number | null;
  permitted_uses?: string[];
  retains_history_after_termination?: boolean | null;
  attribute_group?: string | null;
  time_to_train_days?: number | null;
  replacement_cost_usd?: number | null;
  exception_documented_pct?: number | null;
  automation_pct?: number | null;
  max_downtime_days?: number | null;
  aliases?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Edge".
 */
export interface Edge {
  id: string;
  source: string;
  target: string;
  relation: Relation;
  label?: string | null;
  channel_kind?: ChannelKind | null;
  strength: number;
  strength_range?: [number, number] | null;
  substitutability: number;
  lag_days: number;
  criticality: Criticality;
  confidence: number;
  evidence_refs?: string[];
  extraction_method?: ("seeded" | "keyword" | "zero_shot" | "canary" | "agent") | null;
  last_validated?: string | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Pressure".
 */
export interface Pressure {
  id: string;
  kind: PressureKind;
  name: string;
  target_entity_id: string;
  start_day?: number;
  end_day?: number | null;
  rate?: number | null;
  rate_range?: [number, number] | null;
  step_pct?: number | null;
  monthly_probability?: number | null;
  probability_range?: [number, number] | null;
  cost_per_event_usd?: number | null;
  capacity_sensitivity?: number;
  threshold?: number | null;
  consequence_cost_usd?: number | null;
  neutralised_by?: NeutraliserRef[];
  evidence_refs?: string[];
  description: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "NeutraliserRef".
 */
export interface NeutraliserRef {
  intervention_type: ActionType | MitigationType;
  target_entity_id: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Document".
 */
export interface Document {
  id: string;
  title: string;
  doc_type: DocumentType;
  department_id?: string | null;
  owner_role_id?: string | null;
  uri: string;
  mime_type: string;
  status: DocumentStatus;
  version?: string | null;
  last_reviewed?: string | null;
  review_cycle_days?: number | null;
  sensitivity?: Sensitivity;
  covers_entity_ids?: string[];
  framework_refs?: string[];
  summary: string;
  page_count?: number | null;
  checksum_sha256?: string | null;
  synthetic?: boolean;
  ingested?: boolean;
  uploaded_at: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Evidence".
 */
export interface Evidence {
  id: string;
  source_type: EvidenceSource;
  document_id: string;
  location?: string | null;
  snippet: string;
  synthetic?: boolean;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "OrganizationSettings".
 */
export interface OrganizationSettings {
  settings_id?: string;
  organization_id?: string | null;
  settings_version?: number;
  updated_by?: string;
  updated_at?: string;
  display_currency?: string;
  money_display_scale?: "auto" | "K" | "M" | "B";
  timezone?: string;
  locale?: string;
  default_horizon_days?: number;
  default_futures?: Future[];
  default_delay_days?: number;
  mc_samples?: number;
  default_seed?: number;
  propagation_max_hops?: number;
  min_impact_threshold?: number;
  risk_appetite?: RiskAppetite;
  risk_level_thresholds?: RiskLevelThresholds;
  risk_weights?: RiskWeights;
  optimizer_objective?: "max_net_value" | "min_risk" | "balanced";
  default_constraints?: Constraint[];
  always_protected_entity_ids?: string[];
  require_human_approval?: true;
  anonymize_people?: true;
  enabled_agent_ids?: string[];
  llm_mode?: "live" | "replay" | "mock";
  model_id_strong?: string | null;
  model_id_fast?: string | null;
  max_tool_calls?: number;
  temperature?: number;
  agent_timeout_seconds?: number;
  doc_staleness_days?: number;
  required_doc_types_per_workflow?: DocumentType[];
  sector_preset_id?: string | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "RiskLevelThresholds".
 */
export interface RiskLevelThresholds {
  medium?: number;
  high?: number;
  critical?: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "RiskWeights".
 */
export interface RiskWeights {
  financial?: number;
  capability_workflow?: number;
  customer_revenue?: number;
  compliance_control?: number;
  execution_uncertainty?: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Constraint".
 */
export interface Constraint {
  id: string;
  metric:
    | "annual_savings_usd"
    | "net_value_usd"
    | "revenue_impact_pct"
    | "customer_impact_pct"
    | "compliance_controls_broken"
    | "stranded_workflows"
    | "critical_systems_degraded"
    | "max_capacity_loss_pct"
    | "critical_coverage_pct";
  operator: "<=" | ">=" | "==";
  threshold: number;
  unit: string;
  hard: boolean;
  scope_entity_id?: string | null;
  description: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "SectorPreset".
 */
export interface SectorPreset {
  id: string;
  sector: Sector;
  mandatory_frameworks?: string[];
  default_constraints?: Constraint[];
  risk_weights?: RiskWeights | null;
  pressure_templates?: Pressure[];
  typical_departments?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AgentView".
 */
export interface AgentView {
  agent_id: string;
  twin_version: string;
  organization: Organization;
  department_profile?: DepartmentProfile | null;
  other_department_summaries?: DepartmentSummary[];
  entities?: Entity[];
  edges?: Edge[];
  pressures?: Pressure[];
  documents?: Document[];
  evidence?: Evidence[];
  redacted_entity_count?: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DepartmentSummary".
 */
export interface DepartmentSummary {
  department_id: string;
  mission: string;
  strength_names?: string[];
  staffing: StaffingStrength;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ValidationIssue".
 */
export interface ValidationIssue {
  rule: number | string;
  severity: "error" | "warning";
  message: string;
  ids?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DomainGraph".
 */
export interface DomainGraph {
  nodes?: Entity[];
  edges?: Edge[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DepartmentDetail".
 */
export interface DepartmentDetail {
  entity: Entity;
  profile: DepartmentProfile;
  owned_entities?: Entity[];
  documents?: Document[];
  channels_in?: Edge[];
  channels_out?: Edge[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DecisionBrief".
 */
export interface DecisionBrief {
  schema_version?: "2.1.0" | "2.1.1";
  decision_id: string;
  decision_type: DecisionType;
  title: string;
  statement: string;
  goal: Goal;
  horizon_days?: number;
  candidate_interventions: Intervention[];
  protected_entity_ids?: string[];
  constraints?: Constraint[];
  futures?: Future[];
  delay_days?: number;
  active_pressure_ids?: string[] | null;
  seed?: number;
  mc_samples?: number;
  created_by: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Goal".
 */
export interface Goal {
  metric: string;
  target: number;
  unit?: string;
  basis?: "gross" | "net";
  direction?: "at_least" | "at_most";
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Intervention".
 */
export interface Intervention {
  id: string;
  kind: InterventionKind;
  type: ActionType | MitigationType;
  target_entity_id: string;
  amount_pct?: number | null;
  amount_usd?: number | null;
  start_day?: number;
  duration_days?: number | null;
  one_time_cost_usd?: number;
  new_owner_id?: string | null;
  params?: {
    [k: string]: unknown;
  };
  rationale: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "CandidatePlan".
 */
export interface CandidatePlan {
  plan_id: string;
  label: string;
  intervention_ids: string[];
  source: "naive" | "enumerated" | "optimizer" | "agent" | "user" | "mitigated";
  parent_plan_id?: string | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Scenario".
 */
export interface Scenario {
  scenario_id: string;
  run_id: string;
  future: Future;
  plan_id?: string | null;
  delay_days: number;
  baseline_twin_version: string;
  created_at: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Impact".
 */
export interface Impact {
  impact_id: string;
  decision_id: string;
  scenario_id: string;
  source_entity: string;
  source_kind: "intervention" | "pressure";
  source_ref: string;
  affected_entity: string;
  affected_department?: string | null;
  level: ImpactLevel;
  category: ImpactCategory;
  polarity: Polarity;
  direction: Direction;
  metric: string;
  magnitude: number;
  unit: string;
  value_usd?: number | null;
  severity: number;
  first_effect_day: number;
  peak_effect_day: number;
  confidence: number;
  dependency_path?: string[];
  edge_path?: string[];
  evidence_refs?: string[];
  assumptions?: string[];
  constraint_refs?: string[];
  origin: Origin;
  status: ClaimStatus;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "SimulationResult".
 */
export interface SimulationResult {
  result_id: string;
  run_id: string;
  scenario_id: string;
  future: Future;
  plan_id?: string | null;
  mode: "quick" | "full";
  seed?: number | null;
  intervention_ids?: string[];
  value: ValueBreakdown;
  goal_met: boolean;
  constraint_results?: ConstraintResult[];
  impacts?: Impact[];
  workflow_coverage?: WorkflowCoverage[];
  knowledge_coverage?: KnowledgeCoverage[];
  pressures_triggered?: PressureTrigger[];
  risk: RiskScore;
  affected_department_ids?: string[];
  feasible: boolean;
  rejection_reasons?: string[];
  assumptions?: string[];
  computed_at: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ValueBreakdown".
 */
export interface ValueBreakdown {
  gross_savings_usd: number;
  transition_cost_usd: number;
  added_cost_usd: number;
  rebound_cost_usd: number;
  expected_business_loss_usd: number;
  pressure_cost_usd: number;
  avoided_failure_cost_usd: number;
  net_value_usd: number;
  monthly_net_usd?: number[];
  p10_net_value_usd?: number | null;
  p50_net_value_usd?: number | null;
  p90_net_value_usd?: number | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ConstraintResult".
 */
export interface ConstraintResult {
  constraint_id: string;
  metric:
    | "annual_savings_usd"
    | "net_value_usd"
    | "revenue_impact_pct"
    | "customer_impact_pct"
    | "compliance_controls_broken"
    | "stranded_workflows"
    | "critical_systems_degraded"
    | "max_capacity_loss_pct"
    | "critical_coverage_pct";
  operator: "<=" | ">=" | "==";
  threshold: number;
  value: number;
  hard: boolean;
  passed: boolean;
  explanation: string;
  impact_ids?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "WorkflowCoverage".
 */
export interface WorkflowCoverage {
  workflow_id: string;
  criticality: Criticality;
  owners_before?: string[];
  owners_after?: string[];
  min_qualified_owners: number;
  backup_count_after: number;
  documented_pct: number;
  stranded: boolean;
  reasons?: string[];
  owner_capacity_fte_before?: number | null;
  owner_capacity_fte_after?: number | null;
  exception_documented_pct?: number | null;
  automation_pct?: number | null;
  training_days_required?: number | null;
  replacement_cost_usd?: number | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "KnowledgeCoverage".
 */
export interface KnowledgeCoverage {
  knowledge_id: string;
  holders_before?: string[];
  holders_after?: string[];
  holder_capacity_fte_before: number;
  holder_capacity_fte_after: number;
  documented_pct: number;
  lost: boolean;
  dependent_workflow_ids?: string[];
  reasons?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "PressureTrigger".
 */
export interface PressureTrigger {
  pressure_id: string;
  expected_events: number;
  expected_cost_usd: number;
  neutralised: boolean;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "RiskScore".
 */
export interface RiskScore {
  score: number;
  level: RiskLevel;
  settings_version: number;
  components: RiskComponents;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "RiskComponents".
 */
export interface RiskComponents {
  financial: number;
  capability_workflow: number;
  customer_revenue: number;
  compliance_control: number;
  execution_uncertainty: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "FutureComparison".
 */
export interface FutureComparison {
  comparison_id: string;
  decision_id: string;
  run_id: string;
  reference_result_id: string;
  rows: FutureRow[];
  best_row_index?: number | null;
  headline: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "FutureRow".
 */
export interface FutureRow {
  future: Future;
  plan_id?: string | null;
  result_id: string;
  label: string;
  net_value_p50_usd: number;
  delta_vs_inaction_p10_usd: number;
  delta_vs_inaction_p50_usd: number;
  delta_vs_inaction_p90_usd: number;
  p_better_than_inaction: number;
  breakeven_day?: number | null;
  cost_of_delay_usd?: number | null;
  feasible: boolean;
  risk_score: number;
  monthly_delta_usd?: number[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "PortfolioComparison".
 */
export interface PortfolioComparison {
  evaluated_count: number;
  naive: Portfolio;
  recommended?: Portfolio | null;
  alternatives?: Portfolio[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Portfolio".
 */
export interface Portfolio {
  plan_id: string;
  intervention_ids?: string[];
  rank?: number | null;
  result: SimulationResult;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "MitigationComparison".
 */
export interface MitigationComparison {
  plan_id_before: string;
  plan_id_after: string;
  actions: Intervention[];
  before: SimulationResult;
  after: SimulationResult;
  restored_entity_ids?: string[];
  changed_metrics?: string[];
  feasible_before: boolean;
  feasible_after: boolean;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "BlastRadius".
 */
export interface BlastRadius {
  run_id: string;
  scenario_id: string;
  future: Future;
  plan_id?: string | null;
  root_node_id: string;
  nodes?: BlastNode[];
  edges?: BlastEdge[];
  departments?: DepartmentImpactSummary[];
  outcome: CompanyOutcome;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "BlastNode".
 */
export interface BlastNode {
  node_id: string;
  kind: "decision" | "department" | "entity" | "pressure" | "outcome";
  department_id?: string | null;
  entity_id?: string | null;
  pressure_id?: string | null;
  headline: string;
  level?: ImpactLevel | null;
  category?: ImpactCategory | null;
  polarity?: Polarity | null;
  severity?: number | null;
  value_usd?: number | null;
  first_effect_day?: number | null;
  impact_ids?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "BlastEdge".
 */
export interface BlastEdge {
  source: string;
  target: string;
  label: string;
  level?: ImpactLevel | null;
  critical_constraint: boolean;
  channel_id?: string | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DepartmentImpactSummary".
 */
export interface DepartmentImpactSummary {
  department_id: string;
  headline: string;
  polarity: Polarity;
  severity: number;
  impact_ids?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "CompanyOutcome".
 */
export interface CompanyOutcome {
  net_value_usd: number;
  risk_level: RiskLevel;
  headline: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "VendorOverlap".
 */
export interface VendorOverlap {
  vendor_a: string;
  vendor_b: string;
  dimensions: {
    [k: string]: number;
  };
  overall_overlap: number;
  shared_dataset_ids?: string[];
  unique_dataset_ids_a?: string[];
  unique_dataset_ids_b?: string[];
  migration_difficulty: MigrationDifficulty;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ItemCounterfactual".
 */
export interface ItemCounterfactual {
  intervention_id: string;
  contribution_usd: number;
  net_value_without_usd: number;
  goal_still_met: boolean;
  verdict: "keep" | "drop" | "borderline";
  explanation: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "MissingQuestion".
 */
export interface MissingQuestion {
  question_id: string;
  text: string;
  uncertain_input: string;
  current_assumption: string;
  answer_type: "boolean" | "number" | "choice";
  options?: string[];
  changes_recommendation_if: string;
  value_gap_usd: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "UserAnswer".
 */
export interface UserAnswer {
  question_id: string;
  value: boolean | number | string;
  answered_by: string;
  answered_at: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AgentSpec".
 */
export interface AgentSpec {
  agent_id: string;
  display_name: string;
  department_id?: string | null;
  responsibilities?: string[];
  owned_metrics?: string[];
  visible_entity_types?: EntityType[];
  visible_sensitivity?: Sensitivity[];
  routes_for?: (DecisionType | "all")[];
  prompt_version: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AgentContext".
 */
export interface AgentContext {
  schema_version?: "2.1.0" | "2.1.1";
  run_id: string;
  agent: AgentSpec;
  brief: DecisionBrief;
  plan: CandidatePlan;
  view: AgentView;
  act_now_effects?: Impact[];
  inaction_effects?: Impact[];
  known_impact_summaries?: string[];
  settings: AgentSettingsView;
  max_tool_calls?: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AgentSettingsView".
 */
export interface AgentSettingsView {
  risk_appetite: RiskAppetite;
  optimizer_objective: "max_net_value" | "min_risk" | "balanced";
  display_currency: string;
  money_display_scale: "auto" | "K" | "M" | "B";
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AgentOutput".
 */
export interface AgentOutput {
  affected_entities?: string[];
  act_now_view: FutureView;
  inaction_view: FutureView;
  proposed_dependencies?: ProposedDependency[];
  questions?: AgentQuestion[];
  objections?: Objection[];
  assumptions?: string[];
  evidence_refs?: string[];
  confidence: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "FutureView".
 */
export interface FutureView {
  summary: string;
  failure_modes?: Finding[];
  edge_cases?: Finding[];
  proposed_impacts?: ProposedImpact[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Finding".
 */
export interface Finding {
  text: string;
  entity_ids?: string[];
  severity: number;
  evidence_refs?: string[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ProposedImpact".
 */
export interface ProposedImpact {
  affected_entity: string;
  metric: string;
  direction: Direction;
  polarity: Polarity;
  category: ImpactCategory;
  level: ImpactLevel;
  estimated_magnitude?: number | null;
  unit?: string | null;
  first_effect_day?: number | null;
  severity: number;
  rationale: string;
  dependency_path?: string[];
  evidence_refs?: string[];
  confidence: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ProposedDependency".
 */
export interface ProposedDependency {
  source: string;
  target: string;
  relation: Relation;
  rationale: string;
  evidence_refs?: string[];
  confidence: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AgentQuestion".
 */
export interface AgentQuestion {
  text: string;
  why_it_matters: string;
  entity_ids?: string[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Objection".
 */
export interface Objection {
  target_ref: string;
  text: string;
  severity: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ChallengerOutput".
 */
export interface ChallengerOutput {
  missing_agents?: string[];
  unsupported_assumptions?: Finding[];
  circular_logic?: Finding[];
  overlooked_combinations?: string[][];
  missed_dependencies?: ProposedDependency[];
  inaction_underestimated?: Finding[];
  objections?: Objection[];
  confidence: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AgentAssessment".
 */
export interface AgentAssessment {
  assessment_id: string;
  run_id: string;
  plan_id?: string | null;
  agent_id: string;
  pass_type: "first_pass" | "challenge";
  status: "ok" | "replayed" | "fallback_cached" | "unavailable" | "invalid";
  output?: AgentOutput | null;
  challenge?: ChallengerOutput | null;
  accepted_impacts?: Impact[];
  validation?: ValidationReport;
  metrics: CallMetrics;
  created_at: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ValidationReport".
 */
export interface ValidationReport {
  rejected_entity_ids?: string[];
  downgraded_to_hypothesis?: string[];
  clamped_fields?: string[];
  retries?: number;
  errors?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "CallMetrics".
 */
export interface CallMetrics {
  model_id: string;
  prompt_version: string;
  prompt_hash: string;
  latency_ms: number;
  input_tokens: number;
  output_tokens: number;
  tool_calls?: ToolCall[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ToolCall".
 */
export interface ToolCall {
  name: string;
  args?: {
    [k: string]: unknown;
  };
  ok: boolean;
  result_summary: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DecisionPackage".
 */
export interface DecisionPackage {
  schema_version?: "2.1.0" | "2.1.1";
  package_id: string;
  run_id: string;
  decision_id: string;
  versions: VersionInfo;
  brief: DecisionBrief;
  recommendation?: Recommendation | null;
  futures: FutureComparison;
  portfolios: PortfolioComparison;
  blast_radius_act_now: BlastRadius;
  blast_radius_inaction: BlastRadius;
  department_impacts?: DepartmentImpactSummary[];
  critical_risks?: Impact[];
  mitigations?: MitigationComparison[];
  vendor_overlaps?: VendorOverlap[];
  counterfactuals?: ItemCounterfactual[];
  missing_information?: MissingQuestion[];
  implementation?: ImplementationStep[];
  monitoring?: MonitorRule[];
  assumptions?: string[];
  open_questions?: string[];
  missing_perspectives?: string[];
  status?: "awaiting_approval" | "approved" | "rejected" | "another_scenario_requested";
  created_at: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Recommendation".
 */
export interface Recommendation {
  plan_id: string;
  future: Future;
  result_id: string;
  headline: string;
  claims?: Claim[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Claim".
 */
export interface Claim {
  text: string;
  source: "calculation" | "evidence" | "assumption" | "agent_validated";
  ref: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ImplementationStep".
 */
export interface ImplementationStep {
  order: number;
  day: number;
  action: string;
  intervention_id?: string | null;
  gate?: string | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "MonitorRule".
 */
export interface MonitorRule {
  metric: string;
  entity_id?: string | null;
  operator: "<=" | ">=" | "==";
  threshold: number;
  action: "watch" | "pause" | "rollback" | "escalate";
  description: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "HumanDecision".
 */
export interface HumanDecision {
  run_id: string;
  package_id: string;
  decision: "approve" | "reject" | "request_scenario";
  decided_by: string;
  decided_at: string;
  notes?: string;
  package_hash: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  schema_version?: "2.1.0" | "2.1.1";
  event_id: string;
  run_id: string;
  sequence: number;
  type: EventType;
  actor: string;
  scenario_id?: string | null;
  future?: Future | null;
  timestamp: string;
  payload:
    | DecisionBrief
    | PhaseChanged
    | Scenario
    | PressureActivated
    | CandidatePlan
    | CandidateRejected
    | AgentStarted
    | AgentAssessment
    | AgentFailed
    | DependencyValidated
    | Impact
    | ConstraintResult
    | SimulationResult
    | FutureComparison
    | PortfolioComparison
    | BlastRadius
    | MitigationComparison
    | DecisionPackage
    | HumanDecision
    | MissingQuestion
    | UserAnswer
    | SettingsUpdated
    | Document
    | RunFailed;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "PhaseChanged".
 */
export interface PhaseChanged {
  from_status: RunStatus;
  to_status: RunStatus;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "PressureActivated".
 */
export interface PressureActivated {
  pressure_id: string;
  future: Future;
  expected_cost_usd: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "CandidateRejected".
 */
export interface CandidateRejected {
  plan_id: string;
  reasons: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AgentStarted".
 */
export interface AgentStarted {
  agent_id: string;
  plan_id?: string | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AgentFailed".
 */
export interface AgentFailed {
  agent_id: string;
  reason: string;
  fallback_used: boolean;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DependencyValidated".
 */
export interface DependencyValidated {
  assessment_id: string;
  edge: Edge;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "SettingsUpdated".
 */
export interface SettingsUpdated {
  settings_version: number;
  changed_fields: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "RunFailed".
 */
export interface RunFailed {
  reason: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "RunState".
 */
export interface RunState {
  schema_version?: "2.1.0" | "2.1.1";
  run_id: string;
  decision_id: string;
  baseline_twin_version: string;
  status: RunStatus;
  scenario_ids?: string[];
  candidate_plan_ids?: string[];
  assessment_ids?: string[];
  result_ids?: string[];
  comparison_id?: string | null;
  package_id?: string | null;
  last_sequence?: number;
  created_at: string;
  updated_at: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "HealthResponse".
 */
export interface HealthResponse {
  status?: "ok" | "degraded";
  schema_version?: "2.1.0" | "2.1.1";
  storage?: "file" | "postgres";
  storage_write_failures?: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DecisionCreated".
 */
export interface DecisionCreated {
  run_id: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DecisionPromptRequest".
 */
export interface DecisionPromptRequest {
  prompt: string;
  horizon_days?: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "DecisionDraft".
 */
export interface DecisionDraft {
  brief: DecisionBrief;
  matched_entity_ids?: string[];
  assumptions?: string[];
  warnings?: string[];
  assessing_department_ids?: string[];
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "HumanDecisionRequest".
 */
export interface HumanDecisionRequest {
  decision: "approve" | "reject" | "request_scenario";
  decided_by?: string | null;
  notes?: string;
  package_hash: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "QuickSimulateRequest".
 */
export interface QuickSimulateRequest {
  brief: DecisionBrief;
  intervention_ids?: string[] | null;
  future?: Future;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "FuturesRequest".
 */
export interface FuturesRequest {
  brief: DecisionBrief;
  intervention_ids?: string[] | null;
  futures?: Future[] | null;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "OptimizeRequest".
 */
export interface OptimizeRequest {
  brief: DecisionBrief;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ReplayInfo".
 */
export interface ReplayInfo {
  name: string;
  decision_id?: string | null;
  event_count: number;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "ReplayStarted".
 */
export interface ReplayStarted {
  run_id: string;
  name: string;
  speed: 1 | 2 | 4;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "OrganizationProfileView".
 */
export interface OrganizationProfileView {
  schema_version?: "2.1.0" | "2.1.1";
  organization: Organization;
  departments: OrganizationDepartmentSummary[];
  settings: OrganizationSettings;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "OrganizationDepartmentSummary".
 */
export interface OrganizationDepartmentSummary {
  department_id: string;
  name: string;
  mission: string;
  actual_fte: number;
  annual_budget_usd: number;
  utilisation: number;
  maturity_level: number;
  enabled: boolean;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "SignupRequest".
 */
export interface SignupRequest {
  email: string;
  password: string;
  display_name: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "LoginRequest".
 */
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "UserPublic".
 */
export interface UserPublic {
  user_id: string;
  email: string;
  display_name: string;
  role: UserRole;
  created_at: string;
}
/**
 * This interface was referenced by `CanaryContracts`'s JSON-Schema
 * via the `definition` "AuthToken".
 */
export interface AuthToken {
  access_token: string;
  token_type?: "bearer";
  expires_at: string;
  user: UserPublic;
}
