import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from contracts_py import agents, api, decision, engine, events, package, twin

ROOT = Path(__file__).resolve().parents[4]
CONTRACTS = ROOT / "packages" / "contracts"
SCHEMAS = CONTRACTS / "schemas"
GENERATED_TS = CONTRACTS / "src" / "generated.ts"
BANNER = "/* Generated by `uv run python -m contracts_py.export` from packages/contracts-py. Do not edit. */"

TOP_LEVEL: list[type[BaseModel]] = [
    twin.Twin,
    twin.Organization,
    twin.DepartmentProfile,
    twin.Entity,
    twin.Edge,
    twin.Pressure,
    twin.Document,
    twin.Evidence,
    twin.OrganizationSettings,
    twin.SectorPreset,
    twin.AgentView,
    twin.ValidationIssue,
    twin.DomainGraph,
    twin.DepartmentDetail,
    decision.DecisionBrief,
    decision.Intervention,
    decision.Constraint,
    decision.CandidatePlan,
    decision.Scenario,
    engine.Impact,
    engine.SimulationResult,
    engine.FutureComparison,
    engine.PortfolioComparison,
    engine.MitigationComparison,
    engine.BlastRadius,
    engine.ItemCounterfactual,
    engine.MissingQuestion,
    engine.UserAnswer,
    agents.AgentSpec,
    agents.AgentContext,
    agents.AgentOutput,
    agents.ChallengerOutput,
    agents.AgentAssessment,
    package.DecisionPackage,
    package.HumanDecision,
    events.Event,
    events.EventLog,
    events.RunState,
    api.HealthResponse,
    api.DecisionCreated,
    api.HumanDecisionRequest,
    api.QuickSimulateRequest,
    api.FuturesRequest,
    api.OptimizeRequest,
    api.ReplayInfo,
    api.ReplayStarted,
    api.OrganizationProfileView,
]


def kebab(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def write_schemas() -> list[Path]:
    SCHEMAS.mkdir(parents=True, exist_ok=True)
    written = []
    for model in TOP_LEVEL:
        path = SCHEMAS / f"{kebab(model.__name__)}.schema.json"
        path.write_text(json.dumps(model.model_json_schema(), indent=2) + "\n")
        written.append(path)
    return written


def normalise_for_ts(schema: object) -> object:
    # json2ts emits an extra alias for every field title and for every $ref with siblings
    # (TwinVersion, Criticality1, ...), and ignores prefixItems, so normalise before generating.
    if isinstance(schema, list):
        return [normalise_for_ts(item) for item in schema]
    if not isinstance(schema, dict):
        return schema
    if "$ref" in schema:
        return {"$ref": schema["$ref"]}
    out = {k: normalise_for_ts(v) for k, v in schema.items() if k not in ("title", "properties", "prefixItems")}
    if "prefixItems" in schema:
        out["items"] = normalise_for_ts(schema["prefixItems"])
    if "properties" in schema:
        out["properties"] = {name: normalise_for_ts(prop) for name, prop in schema["properties"].items()}
    return out


def combined_schema() -> dict:
    _, defs = models_json_schema([(m, "validation") for m in TOP_LEVEL], ref_template="#/$defs/{model}")
    names = [m.__name__ for m in TOP_LEVEL]
    return {
        "title": "CanaryContracts",
        "type": "object",
        "properties": {name: {"$ref": f"#/$defs/{name}"} for name in names},
        "required": names,
        "additionalProperties": False,
        "$defs": {name: {**normalise_for_ts(d), "title": name} for name, d in defs["$defs"].items()},
    }


def json2ts_command() -> list[str]:
    binary = CONTRACTS / "node_modules" / ".bin" / "json2ts"
    if not binary.exists():
        pnpm = shutil.which("pnpm")
        if pnpm is None:
            sys.exit("pnpm is required to generate TypeScript types")
        subprocess.run([pnpm, "install", "--filter", "@canary-pact/contracts"], cwd=ROOT, check=True)
    return [str(binary), "--unknownAny", "--unreachableDefinitions", f"--bannerComment={BANNER}"]


def write_typescript() -> None:
    result = subprocess.run(
        json2ts_command(),
        input=json.dumps(combined_schema()),
        capture_output=True,
        text=True,
        cwd=CONTRACTS,
        check=False,
    )
    if result.returncode != 0:
        sys.exit(f"json2ts failed:\n{result.stderr}")
    GENERATED_TS.write_text(result.stdout)


def main() -> None:
    schemas = write_schemas()
    write_typescript()
    print(f"wrote {len(schemas)} schemas to {SCHEMAS.relative_to(ROOT)} and {GENERATED_TS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
